[package]
name = "rvos"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rvos"
path = "src/kmain.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
embedded-io = "0.6.1"