[build]
target = "riscv64gc-unknown-none-elf"
rustflags = [
    '-Clink-arg=-Tsrc/lds/virt.lds'
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-none-elf]
# This runner command is broken into a multiline array for readability.
# Cargo will concatenate these strings into a single command when you run `cargo run`.

runner = [
    "qemu-system-riscv64",
    "-machine", "virt",
    "-cpu", "rv64",
    "-smp", "4",
    "-m", "128M",
    "-bios", "none",
    "-nographic",
    "-serial", "mon:stdio",
    "-dtb",
    "virt.dtb",
    # "-s",
    # "-S",
    "-kernel",
]
